### ISSUE TITLE
Try oauth2-server-php

### ISSUE THREAD

**Issue by zmon** [collabx/IDASH#11]
[oauth2-server-php](https://github.com/bshaffer/oauth2-server-php) is a PHP implementation of a OAuth2 server that supports OpenID Connect at  https://github.com/bshaffer/oauth2-server-php, but when looking through the issues we see things like TokenController does not send id_token, and ID ID Token does not contain user claims.  The [documentation](http://bshaffer.github.io/oauth2-server-php-docs/) looks good.

Notes on how to use with OpenID Connect are at https://github.com/bshaffer/oauth2-server-php-docs/issues/38 skimpy at best.

**Comment by dazzaji** [comment]
I am having trouble understanding what this issue is, what conditions would represent the successful closure of the issue or to whom the issue is assigned.

**Comment by zmon** [comment]
Wrong repo
