### ISSUE TITLE
How to transition UMKC's work to the Prototype Jam and then to NDoCH in KC

### ISSUE THREAD

**Issue by zmon** [collabx/IDASH#12]
For the transition to the Prototype Jam and then to NDoCH were we are going to have coders working on demo code.  The KC NDoCH for the law projects will end in November. I am suggesting the following:
- Setup a repository called OpenIDConnect in the GitHub Organization [UMKCLawTechnologyPublicPolicy](https://github.com/UMKCLawTechnologyPublicPolicy) that @MichaelRobak setup.  I am assuming that we will fork one or more projects into this Organization
  - There would be links to prior work/github repositories in the README
  - Existing repositories would link to this for "code examples" and demos.
- Create add people to the KC Brigade slack or have @MichaelRobak setup a slack.

**Comment by dazzaji** [comment]
The appropriate method is to "fork" repositories that are incubated by an institution and have a head of steam already or that are trans-institution and have people from many different stakeholder groups cohered around a project (that means you would want to fork one or more existing OIDC repositories that your team has a relationship with to the UMKCLawTechnologyPublicPolicy org and be constructive contributors by frequently offering improvements or new work back to the repositories via pull requests.  So, for the legal part of OIDC you would want to fork the MIT SystemRules repo of the HumanDynamics org into the UMKC Law org and you may want to fork the PHP/Wordpress repo that Paul is iterating as well if you plan on doing more technical work.  There is not much in this IDASH repo but you can take whatever files you want and plop them into the UMKC repo.  This IDASH repo will likely have another swell of contributions when  other OIDC projects get rev'd up and so people may find it more attractive to participate in later.  

For the sake of density and also usage, I recommend using CodeForAmerica slack and to extent you can do it, use a channel of the mother ship group (like their brigade or general channels) to remain connected to the big dialog on civic hacking.  

Does that all make sense?  If not, please ask Michael to contact me and I'd be happy to discuss or brainstorm other options if there is desire for something different.  Thanks!
