### ISSUE TITLE
Choose Easy to Adapt "Model" Names

### ISSUE THREAD

**Issue by dazzaji** [collabx/IDASH#8]
I'd like to suggest that when the team writes up the legal rules (contracts, policies etc) for the City IdP multi-city consortium (or federation or association or regional compact or ... whatever it is to be called) you go ahead and use generic names for the roles and also perhaps for the cities and vendors and other described.  This will de-couple the academic and appathon project from city approvals and so forth and enable you to have a more complete thought out draft for review by the various public sector and other groups who may wish to review your work.  Furthermore - it is a good way to design model and extensible, scalable, modular and well engineered sets of rules governing multi-party systems.  

Consider that in the first instance, the people who make decisions, pay for things, approve things, own things like the multi-city identity system... are actually the people who have the right/responsibility to name the thing.  

Whatever the "system owners" decide the system is called is in fact what it is called and the lower level business people and all the legal and technical people then support and reflect the name in their spoken and written work going forward.   Whatever they decide it is called is the what the name is.  That is hard to guess when you are doing a student project and hackathon project.  It can be hard to guess the final name of the thing even just a few years or months before a big project (product, service, statute, etc) is launched.  It can also cause a lot of needless argument when names are chosen too early and distract from substance.  

To address this common issue, a set of "model names" are offered in the "Model Rules" as a starting point.  Other generic rule names are totally cool.  What is important is to be able to map the name of a role in one system to a corresponding role (or roles) in another system. To some extent, it is arbitrary what a role is called and even what a role does.  The underlying dynamic is that "functions" in a system are allocated to "roles".  In an identity system, you can have one operator choose to allocate 5 function to the role "identity proofer" including enrollments, identification verification, account registration and so on while another operator chooses to only allocate three of those roles to the "identity proofer" and to consolidate enrollment with marketing and registration with a product or service (or government program) team.  No problem.  Just know what functions are allocated to what roles and take it from there.  The big functions allocatable to roles should be spelled out in the system rules so any player would know how to adapt.  Some cases may require agreement among all parties that certain roles must minimally have certain clusters of functions - and that is no problem.  Just go with what the system owners and other stakeholders want and need and get explicit when needed.  Between good facilitation and frequent review/update/circulate cycles of review among stakeholders, this sort of stuff can be easily managed, documented and resolved as part of just getting to a version 1.0 set of system rules.  

Recommendation: For now - just call it the thing an "identity system" and the rules "system rules" and you won't get confused and best of all, when the names are chosen or changed, you literally only have a find-replace job to do.  This is also the structure chosen to make the system rules easy to adopt at global, distributed scale - just pop the names of the parties conducting the roles and the set of relationships and transactions and data flows into the template and presto - you have system rules for a system that is ready to rock anywhere in the world.).  

The issue ticket item I would like to propose is that your team simple write down and consistently use the then current version of "Easy to Adapt 'Model' Names.  Maybe use a GitHub file for each name.  Or a Wiki page if you don't want to avail of the deep functionality, version control, global collaboration capability and well documented open REST API based integrations of GitHub for any document system, task management system, or other app/service any collaborator may wish to use for themselves.  Wiki if fine for a start to be sure.  The key thing is to write down each role (maybe as a wiki page titled "Role-IdP" and another called "Role-RP" and "Role-AccountHolder" and "Role-AttributeHolder" and so on.  That will make the rest of your task much simpler and easier to do well!

**Comment by EvanAbsher** [comment]
Got it. I will use GitHub files, I was convinced by your oh so subtle plugging ;).
